config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_comment_counter

  def update_comment_counter
    post.increment!(:commentsCounter)
  end
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likesCounter
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments
  has_many :likes

  after_save :update_post_counter

  def update_post_counter
    user.increment!(:postsCounter)
  end

  def recent_5_comments
    comments.order(updated_at: :desc).limit(5)
  end
  validates :title, presence: true, length: { maximum: 250 }
  validates :commentsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # rubocop:disable ...
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # rubocop:enable ...
  has_many :posts, foreign_key: 'user'
  has_many :likes, foreign_key: 'user'
  has_many :comments, foreign_key: 'user'

  def recent_3_posts
    posts.limit(3).order(created_at: :desc)
  end

  validates :name, presence: true
  validates :postsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :photo, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    post = Post.find(params[:post_id])
    author = post.user
    @comment = Comment.new(comment_params)
    @comment.post = post
    @comment.user = current_user

    render :new unless @comment.save

    redirect_to user_post_url(author, post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    user = current_user
    liked = Like.where(user:, post:)

    return if liked.present?

    like = Like.create(user:, post:)
    return unless like.save

    redirect_to user_post_path(post.user, post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    author = current_user
    @post.user = author

    render :new unless @post.save

    redirect_to user_posts_path(author, @post)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/new.html.erb
<div>
  <h3>Add a comment:</h3>
  <%= form_with model: @comment, url: user_post_comments_url, method: :post do |form| %>
    <%= form.label :text, 'Comment' %>
    <%= form.text_area :text %>
    <%= form.submit 'Post comment' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
  Hey there <strong><%= current_user.name%></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
 <%= button_to( "Log Out", destroy_user_session_path, method: :delete ) %>


<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with model: Like do |form| %>
  <%= form.hidden_field :post_id, value: post_id %>
  <button type="submit" class="submit">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4 text-red-400">
      <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
    </svg>
    <span class="like">Like</span>
  </button>
<% end %>

app/views/posts/_bio_card.html.erb
<div>
  <h2>Bio</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec justo id massa iaculis malesuada. Vestibulum faucibus egestas tempus. Aliquam dapibus rutrum mauris, ac euismod eros vestibulum sit amet. Phasellus volutpat dolor id libero rutrum mattis. Phasellus sagittis erat id nulla faucibus, sed maximus dolor maximus. Praesent sollicitudin leo ut posuere bibendum. Nullam non tempor libero.
    Mauris ultrices sem mollis neque viverra, non cursus neque molestie. Pellentesque interdum suscipit erat sed imperdiet. Donec a turpis sed enim mollis semper. Mauris lacinia erat quis ex hendrerit, dictum ornare odio faucibus. Nam non nunc ex. Maecenas maximus tellus sed ante sodales accumsan. Donec vulputate leo sed varius fermentum. Sed sit amet eleifend est, a finibus elit. Quisque in mauris vehicula, rutrum leo nec, faucibus mauris. Cras in urna mollis risus vehicula accumsan et vitae eros. Fusce ut arcu nisl. In et purus id turpis semper tempor. Suspendisse potenti. Mauris nibh libero, finibus et pretium quis, blandit sit amet ligula. Suspendisse scelerisque dui lacus, sit amet egestas tellus finibus a.</p>
</div>
</div>

app/views/posts/_post_card.html.erb
<div>
<%= link_to user_post_path(post.user, post) do %>
    <h2>Post #<%= post.id%> <%= post.title %></h2>
<% end %>
<p><%= post.text.length > 120 ? post.text.first(100) + '...' : post.text %></p>
<h3>Comments: <%= post.commentCounter %>, Likes: <%= post.likesCounter %></h3>
</div>

app/views/posts/_post_card_comments.erb
<%= render partial: 'posts/post_card', locals: { post: post } %>
<% if comments.any? %>
  <div>
    <% comments.each do |comment| %>
      <div>
        <h3><%= comment.user.name %>: <span><%= comment.text %></span></h3>
      </div>
    <% end %>
  </div>
<% end %>
<% if comments.empty? %>
  <div>
    <div>
      <h3>There no comments for this post!</h3>
    </div>
  </div>
<% end %>

app/views/posts/_post_details.erb
<div>
  <div>
  <h2>Post #<%= post.id%> by <%= post.user.name %></h2>
  <h3>Comments: <%= post.commentsCounter %>, Likes: <%= post.likesCounter %></h3>
  </div>
  <p><%= post.text %></p>
</div>

<% if comments.any? %>
  <div>
    <% comments.each do |comment| %>
      <div>
        <h3><%= comment.user.name %>: <span><%= comment.text %></span></h3>
      </div>
    <% end %>
  </div>
<% end %>
<% if comments.empty? %>
  <div>
    <div>
      <h3>There no comments for this post!</h3>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<div>
  <%= render 'users/user_card'%>

  <div>
    <%= link_to 'Add a new post', new_user_post_path %>
  </div>

  <% @posts.each do |post| %>
    <div class='post-card'>
      <h3><%=link_to post.title, user_post_path(@user.id, post), :class => 'post-title'%></h3>
      <p><%= post.text %></p>
      <div class='likes-comments'>
        <p>Comments: <%= post.commentsCounter.nil? ? 0 : post.commentsCounter %></p>
        <p>Likes: <%= post.likesCounter.nil? ? 0 : post.likesCounter %></p>
      </div>
    </div>
    <div class='comments_cnt'>
      <% post.recent_5_comments.each do |comment| %>
        <p class='comment'><%= comment.user.name %>: <%= comment.text %></p>
      <% end %>
    </div>
  <% end %>
   <button>Pagination</button>
</div>

app/views/posts/new.html.erb
<div>
  <h1>Create a new post:</h1>
  <%= form_with model: @post, url: user_posts_path, method: :post do |form| %>
    <%= form.label :title, 'Title' %>
    <%= form.text_field :title %>
    <%= form.label :text, 'Text' %>
    <%= form.text_area :text %>
    <%= form.submit 'Post' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class='post-card'>
  <div class='post-header'>
    <h3>"<%= @post.title %>" by: <%= @post.user.name %></h3>
    <div class='likes-comments'>
      <p>Comments: <%= @post.commentsCounter.nil? ? 0 : @post.commentsCounter %></p>
      <p>Likes: <%= @post.likesCounter.nil? ? 0 : @post.likesCounter %></p>
    </div>
  </div>
  <p><%= @post.text %></p>
</div>
<div class="buttons">
  <%= link_to 'Add a new comment', new_user_post_comment_path(@user, @post) %>
  <%= button_to 'Like', user_post_likes_path(@user, @post) %>
<div class='comments_cnt'>
  <% @post.comments.each do |comment| %>
    <p><%= comment.user.name %>: <%= comment.text %></p>
  <% end %>
</div>

app/views/users/_user_card.html.erb
<div class='user-card'> 
  <img src=<%= @user.photo %> alt="profile picture" class="user-photo">
  <h2><%= @user.name %></h2>
  <p>Number of posts: <%= @user.postsCounter.nil? ? 0 : @user.postsCounter %></p>
</div>

app/views/users/index.html.erb
<div>
  <% @users.each do |user| %>
    <div class='user-card'>
      <img src=<%= user.photo %> alt="profile picture" class="user-photo">
      <h2><%= link_to user.name, user, :class => 'user-name' %></h2>
      <p>Number of posts: <%= user.postsCounter.nil? ? 0 : user.postsCounter %></p>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div>
  <%= render 'users/user_card'%>

  <div class='user-bio'>
    <h2>Bio</h2>
    <p><%= @user.bio %></p>
  </div>

  <div>
    <%= link_to 'Add a new post', new_user_post_path(@user) %>
  </div>

  <div>
    <% @user. recent_3_posts.each do |post| %>
    <div class='post-card'>
      <h3><%=link_to post.title, user_post_path(@user.id, post), :class => 'post-title'%></h3>
      <p><%= post.text %></p>
      <div class='likes-comments'>
        <p>Comments: <%= post.commentsCounter.nil? ? 0 : post.commentsCounter %></p>
        <p>Likes: <%= post.likesCounter.nil? ? 0 : post.likesCounter %></p>
      </div>
    </div>
  <% end %>
  </div>
  <% unless @user. recent_3_posts.empty? %>
    <button><%=link_to 'See all posts', user_posts_path(@user), :class => 'see-all-btn'%></button>
  <% end %>
</div>